config/routes.rb
Rails.application.routes.draw do
  root "user_sessions#new"

  resources :users
  resources :user_sessions
  resources :posts
  resources :blogs
  resources :comments, except: [:index, :show]

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  content    :string
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :content, presence: true
  validates :user_id, presence: true

  def to_s
    content
  end

  def self.search(search)
    if search
      where("lower(content) LIKE ?", "%#{search.downcase}%")
    else
      self.all
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @text = "Show"
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def index
    @text = "Index"
    @posts = Post.search(params[:search]).order(created_at: :desc).page(params[:page])
  end

  def new
    @text = "New"
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_path(@post)
      flash[:success] = "Post was created!"
    else
      redirect_to new_post_path
      flash[:error] = @post.errors.messages.map{|e| "<i class='fa fa-minus'></i> <strong>#{e.flatten.first.to_s.titleize}</strong> #{e.flatten.last}"}.join('<br />')
    end
  end

  def edit
    @text = "Edit"
    @post = Post.find(params[:id])
    check_authorization(@post)
  end

  def update
    @post = Post.find(params[:id])
    if @post.update post_params
      redirect_to post_path(@post)
      flash[:success] = "Post was saved!"
    else
      redirect_to edit_post_path(@post)
      flash[:error] = @post.errors.messages.map{|e| "<i class='fa fa-minus'></i> <strong>#{e.flatten.first.to_s.titleize}</strong> #{e.flatten.last}"}.join('<br />')
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if check_authorization(@post)
      @post.destroy
      redirect_to root_path
      flash[:success] = "Post was destroyed!"
    end
  end

  private
  def post_params
    if params[:post]
      params[:post][:user_id] = current_user.id
      params.require(:post).permit(:content, :user_id)
    end
  end

  def check_authorization(post)
    unless post.user == current_user
      redirect_to root_path
      flash[:alert] = "Not Authorized"
      return false
    else
      return true
    end
  end
end

app/views/posts/_sidebar.html.erb
<%= content_for :sidebar_content do %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">
        Search
      </h3>
    </div>
    <div class="panel-body">
      <%= form_tag posts_path, method: :get do %>
        <div class="form-group">
          <div class="input-group">
            <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search" %>
            <span class="input-group-btn">
              <%= submit_tag 'Search', class: "btn btn-default" %>
            </span>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>
  <%= link_to fa_icon("arrow-left"), post_path(@post) %>
  <%= @text %>
</h1>

<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control" %>
  </div>
  <%= f.submit "Update Post", class: "btn btn-default" %>
<% end %>

app/views/posts/index.html.erb
<div class="pull-right">
  <%= link_to "New Post", new_post_path, class: "btn btn-primary" %>
</div>
<h1><%= @text %></h1>
<% @posts.each do |post| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">
        <%= post.user.name %>
        <span style="color:#989898">@<%= post.user.username %></span>
        <div class="pull-right">
          <%= link_to "Show", post_path(post) %>
        </div>
      </h3>
    </div>
    <div class="panel-body">
      <%= post %>
      <br>
      <div class="pull-right text-muted">
        <%= post.created_at.to_formatted_s(:long_ordinal) %>
      </div>
    </div>
  </div>
<% end %>

<div class="text-center">
  <%= paginate @posts, theme: "twitter-bootstrap-3" %>
</div>

<%= render 'sidebar' %>

app/views/posts/new.html.erb
<h1>
  <%= link_to fa_icon("arrow-left"), posts_path %>
  <%= @text %>
</h1>

<%= form_for Post.new do |f| %>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control" %>
  </div>
  <%= f.submit "Create New Post", class: "btn btn-default" %>
<% end %>

app/views/posts/show.html.erb
<div class="pull-right">
  <div class="btn-group">
    <%=link_to fa_icon("comment"), new_comment_path(post_id: @post.id), class:"btn btn-primary"%>
    <% if @post.user == current_user %>
      <%=link_to fa_icon("pencil"), edit_post_path(@post), class:"btn btn-default"%>
      <%=link_to fa_icon("trash-o"), post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-danger"%>
    <% end %>
  </div>
</div>
<h1>
 <%= link_to fa_icon("arrow-left"), posts_path %>
 <%= @text %>
</h1>
<div class="media">
 <div class="media-body">
   <h4 class="media-heading"><%= @post.user.name %></h4>
   <%= @post %>
   <br />
   <div class="pull-right text-muted" style="font-size:0.9em;">
     <%= @post.created_at.to_formatted_s(:long_ordinal) %>
   </div>
   <hr />
 </div>
</div>

<% @comments.each do |comment| %>
 <div class="media comment">
   <div class="media-body">
     <h4 class="media-heading">
        <% if comment.user == current_user %>
          <div class="btn-group pull-right">
            <%=link_to fa_icon("pencil"), edit_comment_path(comment), class:"btn btn-default"%>
            <%=link_to fa_icon("trash-o"), comment_path(comment), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-danger"%>
          </div>
       <% end %>
       <%= comment.user.name %>
     </h4>
     <%= comment.content %>
     <br />
     <div class="pull-right text-muted" style="font-size:0.9em;">
       <%= comment.created_at.to_formatted_s(:long_ordinal) %>
     </div>
     <hr />
   </div>
 </div>
<% end %>