config/routes.rb
Rails.application.routes.draw do
  root "user_sessions#new"

  resources :users
  resources :user_sessions
  resources :posts
  resources :blogs
  resources :comments, except: [:index, :show]

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login
  def new
    if current_user
      redirect_to posts_path
    else
      @user = User.new
    end
  end

  def create
    if @user = login(params[:email], params[:password])
      flash[:success] = 'Login successful'
      redirect_to root_path
    else
      redirect_to new_user_session_path
      flash[:alert] = 'Login failed'
    end
  end

  def destroy
    logout
    if cookies[:_tweeter_session] && cookies["rack.session"]
      cookies.delete :_tweeter_session
      cookies.delete :"rack.session"
    end
    redirect_to login_path
    flash[:success] = 'Logged out!'
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>UserSessions#new</h1>
<%= form_tag user_sessions_path, method: :post do %>
  <div class="form-group">
     <%= label_tag :email %><br />
     <%= text_field_tag :email, '', class: "form-control" %>
  </div>
  <div class="form-group">
     <%= label_tag :password %><br />
     <%= password_field_tag :password, '', class: "form-control" %>
  </div>

  <%= submit_tag "Login", class: "btn btn-primary" %>
<% end %>