config/routes.rb
Rails.application.routes.draw do
  root "user_sessions#new"

  resources :users
  resources :user_sessions
  resources :posts
  resources :blogs
  resources :comments, except: [:index, :show]

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweeter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to "Tweeter", root_path, class: "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <% if current_user %>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Blogs", blogs_path %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <p class="navbar-text"><%= "#{current_user.name} (@#{current_user.username})" %></p>
            <li><%= link_to "Log out", logout_path %></li>
          <% else %>
            <li><%= link_to "Create Account", new_user_path %></li>
            <li><%= link_to "Login", login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container-fluid content">
    <%= flash_messages %>
    <div class="row">
      <div class="col-sm-3"></div>
      <div class="col-sm-6">
        <%= yield %>
      </div>
      <div class="side-content col-sm-3">
        <%= yield :sidebar_content %>
      </div>
    </div>
  </div>

</body>
</html>